# Generated by Django 6.0.4 on 2026-05-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_proceso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='link_secop',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link SECOP'),
        ),
    ]
