# Generated by Django 6.0.4 on 2026-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_link_secop'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='tipo_saldo',
            field=models.CharField(blank=True, choices=[('', 'Sin clasificar'), ('A_FAVOR', 'Saldo a Favor'), ('CUENTAS_POR_COBRAR', 'Cuentas por Cobrar')], default='', max_length=30, verbose_name='Tipo de Saldo'),
        ),
    ]
