# Generated by Django 6.0.4 on 2026-05-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_proceso_tipo_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('radicador', 'Radicador'), ('visualizador', 'Visualizador')], default='radicador', max_length=20),
        ),
    ]
